'use strict';
const DATA=window.LICENSE_DATA;
const STORAGE_KEY='license-studio-simple-v1';
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const policyKeys=['commercial','monetized','modification','project','merchandise','redistribution'];
let state=makeDefault();
let saveTimer=null;
function makeDefault(){const base=structuredClone(DATA.defaultState);return {...base,version:'',workUrl:'',language:'ja',includeCoverPage:false,includeDisclaimer:true,customClauses:[],shareAlike:false,softwareScope:'',policies:{...base.policies}}}
const el={saveStatus:$('#saveStatus'),titleInput:$('#titleInput'),creatorInput:$('#creatorInput'),workNameInput:$('#workNameInput'),workTypeSelect:$('#workTypeSelect'),updatedAtInput:$('#updatedAtInput'),contactInput:$('#contactInput'),presetSelect:$('#presetSelect'),policyMatrix:$('#policyMatrix'),creditTextInput:$('#creditTextInput'),noExtractionInput:$('#noExtractionInput'),restrictionAdult:$('#restrictionAdult'),restrictionPolitical:$('#restrictionPolitical'),restrictionAi:$('#restrictionAi'),restrictionNft:$('#restrictionNft'),restrictionHarmful:$('#restrictionHarmful'),restrictionImpersonation:$('#restrictionImpersonation'),notesInput:$('#notesInput'),customSection:$('#customSection'),ccSection:$('#ccSection'),softwareSection:$('#softwareSection'),ccLicenseSelect:$('#ccLicenseSelect'),ccResultCard:$('#ccResultCard'),softwareLicenseSelect:$('#softwareLicenseSelect'),softwareResultCard:$('#softwareResultCard'),softwareScopeInput:$('#softwareScopeInput'),themeSelect:$('#themeSelect'),accentInput:$('#accentInput'),coverInput:$('#coverInput'),coverFileRow:$('#coverFileRow'),coverFileName:$('#coverFileName'),removeCoverButton:$('#removeCoverButton'),downloadPdfButton:$('#downloadPdfButton'),statusMessage:$('#statusMessage'),pdfDocument:$('#pdfDocument'),exportProjectButton:$('#exportProjectButton'),importProjectInput:$('#importProjectInput')};
function init(){load();if(!state.updatedAt)state.updatedAt=new Date().toISOString().slice(0,10);populate();buildMatrix();bind();sync();render();}
function load(){try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(v&&typeof v==='object'){state={...makeDefault(),...v,policies:{...makeDefault().policies,...(v.policies||{})},restrictions:{...makeDefault().restrictions,...(v.restrictions||{})}}}}catch(e){console.warn(e)}}
function populate(){el.workTypeSelect.innerHTML=Object.entries(DATA.workTypes).filter(([k])=>k!=='software').map(([k,v])=>`<option value="${k}">${v.label}</option>`).join('');el.presetSelect.innerHTML=Object.entries(DATA.customPresets).map(([k,v])=>`<option value="${k}">${v.name}</option>`).join('');el.ccLicenseSelect.innerHTML=Object.entries(DATA.ccLicenses).map(([k,v])=>`<option value="${k}">${v.short}</option>`).join('');el.softwareLicenseSelect.innerHTML=Object.entries(DATA.softwareLicenses).map(([k,v])=>`<option value="${k}">${v.short}</option>`).join('')}
function buildMatrix(){const items=DATA.policyItems.filter(x=>policyKeys.includes(x.key));el.policyMatrix.innerHTML=items.map(x=>`<div class="policy-row" data-policy="${x.key}"><div class="policy-info"><span class="policy-icon">${x.icon}</span><span><strong>${x.label}</strong></span></div><div class="policy-choices"><button class="policy-choice" type="button" data-state="allow">許可</button><button class="policy-choice" type="button" data-state="ask">要相談</button><button class="policy-choice" type="button" data-state="deny">禁止</button></div></div>`).join('')}
function bind(){ $$('.mode-button').forEach(b=>b.addEventListener('click',()=>{state.mode=b.dataset.mode;renderSave()})); bindVal(el.titleInput,'title');bindVal(el.creatorInput,'creator');bindVal(el.workNameInput,'workName');bindVal(el.workTypeSelect,'workType','change');bindVal(el.updatedAtInput,'updatedAt','change');bindVal(el.contactInput,'contact');bindVal(el.creditTextInput,'creditText');bindVal(el.notesInput,'notes');bindVal(el.softwareScopeInput,'softwareScope');bindVal(el.themeSelect,'theme','change');
  el.presetSelect.addEventListener('change',()=>applyPreset(el.presetSelect.value));
  el.policyMatrix.addEventListener('click',e=>{const b=e.target.closest('.policy-choice');if(!b)return;state.policies[b.closest('.policy-row').dataset.policy]=b.dataset.state;renderSave()});
  document.querySelectorAll('[data-segment="credit"] button').forEach(b=>b.addEventListener('click',()=>{state.credit=b.dataset.value;renderSave()}));
  document.querySelectorAll('[data-segment="ccCommercial"] button').forEach(b=>b.addEventListener('click',()=>{state.ccCommercial=b.dataset.value==='yes';pickCC();renderSave()}));
  document.querySelectorAll('[data-segment="ccAdaptation"] button').forEach(b=>b.addEventListener('click',()=>{state.ccAdaptation=b.dataset.value;pickCC();renderSave()}));
  [ ['adult',el.restrictionAdult],['political',el.restrictionPolitical],['ai',el.restrictionAi],['nft',el.restrictionNft],['harmful',el.restrictionHarmful],['impersonation',el.restrictionImpersonation] ].forEach(([k,node])=>node.addEventListener('change',()=>{state.restrictions[k]=node.checked;renderSave()}));
  el.noExtractionInput.addEventListener('change',()=>{state.noExtraction=el.noExtractionInput.checked;renderSave()});
  el.ccLicenseSelect.addEventListener('change',()=>{state.ccLicense=el.ccLicenseSelect.value;syncCCQuestions();renderSave()});
  el.softwareLicenseSelect.addEventListener('change',()=>{state.softwareLicense=el.softwareLicenseSelect.value;renderSave()});
  el.accentInput.addEventListener('input',()=>{state.accent=el.accentInput.value;renderSave()});
  el.coverInput.addEventListener('change',readCover);el.removeCoverButton.addEventListener('click',()=>{state.coverImage='';state.coverImageName='';el.coverInput.value='';renderSave()});
  el.downloadPdfButton.addEventListener('click',exportPdf);el.exportProjectButton.addEventListener('click',exportProject);el.importProjectInput.addEventListener('change',importProject);
}
function bindVal(node,key,event='input'){node.addEventListener(event,()=>{state[key]=node.value;renderSave()})}
function sync(){el.titleInput.value=state.title;el.creatorInput.value=state.creator;el.workNameInput.value=state.workName;el.workTypeSelect.value=state.workType;el.updatedAtInput.value=state.updatedAt;el.contactInput.value=state.contact;el.presetSelect.value=state.preset;el.creditTextInput.value=state.creditText;el.notesInput.value=state.notes;el.softwareScopeInput.value=state.softwareScope||'';el.themeSelect.value=state.theme;el.accentInput.value=state.accent;el.ccLicenseSelect.value=state.ccLicense;el.softwareLicenseSelect.value=state.softwareLicense;el.noExtractionInput.checked=!!state.noExtraction;el.restrictionAdult.checked=!!state.restrictions.adult;el.restrictionPolitical.checked=!!state.restrictions.political;el.restrictionAi.checked=!!state.restrictions.ai;el.restrictionNft.checked=!!state.restrictions.nft;el.restrictionHarmful.checked=!!state.restrictions.harmful;el.restrictionImpersonation.checked=!!state.restrictions.impersonation;syncCCQuestions()}
function renderSave(){render();clearTimeout(saveTimer);el.saveStatus.textContent='保存中…';saveTimer=setTimeout(()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));el.saveStatus.textContent='保存済み'},250)}
function applyPreset(key){const p=DATA.customPresets[key];if(!p)return;state.preset=key;state.policies={...state.policies,...p.policies};state.credit=p.credit;state.noExtraction=p.noExtraction;state.restrictions={...state.restrictions,...p.restrictions};sync();renderSave()}
function render(){ $$('.mode-button').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));el.customSection.hidden=state.mode!=='custom';el.ccSection.hidden=state.mode!=='cc';el.softwareSection.hidden=state.mode!=='software';el.coverFileRow.hidden=!state.coverImage;el.coverFileName.textContent=state.coverImageName||'';$$('.policy-row').forEach(row=>row.querySelectorAll('.policy-choice').forEach(b=>b.classList.toggle('active',state.policies[row.dataset.policy]===b.dataset.state)));setSegment('credit',state.credit);setSegment('ccCommercial',state.ccCommercial?'yes':'no');setSegment('ccAdaptation',state.ccAdaptation);renderStandard();renderPdf()}
function setSegment(name,value){document.querySelectorAll(`[data-segment="${name}"] button`).forEach(b=>b.classList.toggle('active',b.dataset.value===value))}
function renderStandard(){const cc=DATA.ccLicenses[state.ccLicense];el.ccResultCard.innerHTML=`<h4>${escapeHTML(cc.short)}</h4><p>${escapeHTML(cc.name)}</p><div class="result-tags">${[...cc.allow,...cc.conditions].slice(0,5).map(x=>`<span>${escapeHTML(x)}</span>`).join('')}</div>`;const sw=DATA.softwareLicenses[state.softwareLicense];el.softwareResultCard.innerHTML=`<h4>${escapeHTML(sw.short)}</h4><p>${escapeHTML(sw.description)}</p><div class="result-tags">${[...sw.allow,...sw.conditions].slice(0,5).map(x=>`<span>${escapeHTML(x)}</span>`).join('')}</div>`}
function pickCC(){const c=state.ccCommercial,a=state.ccAdaptation;if(c&&a==='yes')state.ccLicense='CC-BY-4.0';else if(c&&a==='same')state.ccLicense='CC-BY-SA-4.0';else if(c&&a==='no')state.ccLicense='CC-BY-ND-4.0';else if(!c&&a==='yes')state.ccLicense='CC-BY-NC-4.0';else if(!c&&a==='same')state.ccLicense='CC-BY-NC-SA-4.0';else state.ccLicense='CC-BY-NC-ND-4.0';el.ccLicenseSelect.value=state.ccLicense}
function syncCCQuestions(){const k=state.ccLicense;state.ccCommercial=!k.includes('-NC-');if(k.includes('-ND-'))state.ccAdaptation='no';else if(k.includes('-SA-'))state.ccAdaptation='same';else state.ccAdaptation='yes'}
function readCover(){const f=el.coverInput.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{state.coverImage=String(r.result);state.coverImageName=f.name;renderSave()};r.readAsDataURL(f)}
function renderPdf(){const work=DATA.workTypes[state.workType]||DATA.workTypes.other;let body='';if(state.mode==='custom')body=renderCustom();if(state.mode==='cc')body=renderCC();if(state.mode==='software')body=renderSoftware();const thumb=state.coverImage?`<div class="pdf-thumb"><img src="${state.coverImage}" alt=""></div>`:`<div class="pdf-thumb"><span>${escapeHTML(work.icon)}</span></div>`;el.pdfDocument.innerHTML=`<article class="pdf-page theme-${state.theme}" style="--pdf-accent:${state.accent}"><div class="pdf-inner"><div class="pdf-head"><div><p class="pdf-kicker">LICENSE / TERMS OF USE</p><h1 class="pdf-title">${escapeHTML(state.title||'作品利用ガイド')}</h1><p class="pdf-lead">「${escapeHTML(state.workName||'この作品')}」をどのように使えるか、必要な条件だけをまとめています。</p></div>${thumb}</div><div class="pdf-meta"><div><span>作者</span><strong>${escapeHTML(state.creator||'—')}</strong></div><div><span>作品</span><strong>${escapeHTML(state.workName||'—')}</strong></div><div><span>更新</span><strong>${escapeHTML(state.updatedAt||'—')}</strong></div></div>${body}<div class="pdf-footer"><span>${escapeHTML(state.contact||'')}</span><span>License Studio</span></div></div></article>`}
function renderCustom(){const groups={allow:[],ask:[],deny:[]};DATA.policyItems.filter(x=>policyKeys.includes(x.key)).forEach(x=>groups[state.policies[x.key]].push(x.label));const keys=[keyCard('商用利用',state.policies.commercial,'販売・広告・有料案件'),keyCard('改変・加工',state.policies.modification,'編集・色変更・アレンジ'),keyCard('作品への組み込み',state.policies.project,'ゲーム・動画・Webなど'),keyCard('素材の再配布',state.policies.redistribution,'元データや編集素材の再配布')].join('');const restrictions=restrictionLabels();const extra=[creditSentence(),state.noExtraction?'組み込み先から素材を抜き出して再利用することは禁止です。':'',restrictions.length?`禁止用途: ${restrictions.join('・')}`:'',state.notes||''].filter(Boolean).join('\n');return `<div class="pdf-summary">${summary('allow','✓','できること',groups.allow)}${summary('ask','!','要相談',groups.ask)}${summary('deny','×','禁止',groups.deny)}</div><section class="pdf-section"><div class="pdf-section-title"><span>01</span><h3>大事なルール</h3></div><div class="key-grid">${keys}</div></section><section class="pdf-section"><div class="pdf-section-title"><span>02</span><h3>クレジット・補足</h3></div><div class="note-box">${escapeHTML(extra)}</div></section>`}
function renderCC(){const cc=DATA.ccLicenses[state.ccLicense];return `<div class="pdf-summary">${summary('allow','✓','できること',cc.allow)}${summary('ask','!','条件',cc.conditions)}${summary('deny','×','制限',cc.deny.length?cc.deny:['追加の制限なし'])}</div><section class="pdf-section"><div class="pdf-section-title"><span>01</span><h3>${escapeHTML(cc.short)}</h3></div><div class="note-box">${escapeHTML(`「${state.workName||'この作品'}」は ${cc.name} の条件で提供されます。\n\n表示例: ${state.workName||'Work'} © ${state.creator||'Creator'} — ${cc.short}\n${cc.url}`)}</div></section>`}
function renderSoftware(){const sw=DATA.softwareLicenses[state.softwareLicense];return `<div class="pdf-summary">${summary('allow','✓','許可',sw.allow)}${summary('ask','!','条件',sw.conditions)}${summary('deny','×','制限',sw.limitations)}</div><section class="pdf-section"><div class="pdf-section-title"><span>01</span><h3>${escapeHTML(sw.short)}</h3></div><div class="note-box">${escapeHTML(sw.description)}${state.softwareScope?`\n\n適用範囲: ${escapeHTML(state.softwareScope)}`:''}\n\n${escapeHTML(sw.url)}</div></section>`}
function summary(kind,symbol,title,items){return `<div class="pdf-summary-card ${kind}"><span class="summary-symbol">${symbol}</span><h3>${title}</h3><ul>${(items.length?items:['なし']).slice(0,5).map(x=>`<li>${escapeHTML(x)}</li>`).join('')}</ul></div>`}
function keyCard(title,status,desc){return `<div class="key-card"><span class="key-icon">${status==='allow'?'✓':status==='ask'?'!':'×'}</span><span><strong>${title}: ${statusText(status)}</strong><small>${desc}</small></span></div>`}
function statusText(s){return s==='allow'?'許可':s==='ask'?'要相談':'禁止'}
function creditSentence(){if(state.credit==='required')return `クレジット表記は必須です。${state.creditText?` 表記例: ${state.creditText}`:''}`;if(state.credit==='recommended')return `クレジット表記を推奨します。${state.creditText?` 表記例: ${state.creditText}`:''}`;return 'クレジット表記は不要です。'}
function restrictionLabels(){const m={adult:'成人向け',political:'政治・宗教',ai:'AI学習',nft:'NFT',harmful:'違法・中傷',impersonation:'公式を装う利用'};return Object.entries(state.restrictions).filter(([,v])=>v).map(([k])=>m[k])}
async function exportPdf(){try{if(!window.html2canvas||!window.jspdf?.jsPDF)throw new Error('PDF生成ライブラリを読み込めませんでした。');setStatus('PDFを生成しています…');el.downloadPdfButton.disabled=true;const page=$('.pdf-page');const clone=page.cloneNode(true);const host=document.createElement('div');host.style.cssText='position:fixed;left:-10000px;top:0;width:794px;height:1123px;z-index:-1;';clone.style.transform='none';clone.style.margin='0';host.appendChild(clone);document.body.appendChild(host);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const canvas=await html2canvas(clone,{scale:2,useCORS:true,backgroundColor:null,logging:false});host.remove();const {jsPDF}=window.jspdf;const pdf=new jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true});pdf.addImage(canvas.toDataURL('image/jpeg',.96),'JPEG',0,0,210,297,undefined,'FAST');pdf.setProperties({title:state.title||'License',author:state.creator||'License Studio',creator:'License Studio'});pdf.save(`${safeFilename(state.workName||state.title||'license')}-license.pdf`);setStatus('PDFを書き出しました。')}catch(e){console.error(e);setStatus(e.message||'PDFの生成に失敗しました。',true)}finally{el.downloadPdfButton.disabled=false}}
function exportProject(){downloadBlob(new Blob([JSON.stringify(state,null,2)],{type:'application/json;charset=utf-8'}),`${safeFilename(state.workName||'license')}.license-studio.json`)}
function importProject(){const f=el.importProjectInput.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const v=JSON.parse(String(r.result));state={...makeDefault(),...v,policies:{...makeDefault().policies,...(v.policies||{})},restrictions:{...makeDefault().restrictions,...(v.restrictions||{})}};sync();renderSave();setStatus('設定を読み込みました。')}catch{setStatus('設定を読み込めませんでした。',true)}finally{el.importProjectInput.value=''}};r.readAsText(f)}
function downloadBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1200)}
function safeFilename(v){return String(v).replace(/[\\/:*?"<>|]/g,'').trim().replace(/\s+/g,'-')||'license'}
function setStatus(m,e=false){el.statusMessage.textContent=m;el.statusMessage.classList.toggle('error',!!e)}
function escapeHTML(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
document.addEventListener('DOMContentLoaded',init);
